spring:
  datasource:
    hikari:
      connectionTimeout: "20000"
      maximumPoolSize: "5"
    url: "jdbc:postgresql://rpgtracker-coc-db:5432/rpgtracker-coc?currentSchema=public"
    username: "postgres"
    password: "postgres"
    driver-class-name: "org.postgresql.Driver"
  liquibase:
    change-log: "classpath:db/master-coc.json"
    parameters:
      uuid_function:
        name: "uuid_function"
        value: "gen_random_uuid()"
  jpa:
    show-sql: "false"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://keycloak:8080/realms/HBsites/protocol/openid-connect/certs"
  rabbitmq:
    host: "rabbitmq"
    port: "5672"
    username: "rpgtracker-coc"
    password: "rpgtracker-coc"
server:
  port: "8082"
