spring:
  datasource:
    hikari:
      connectionTimeout: "20000"
      maximumPoolSize: "5"
    url: "jdbc:h2:~/testcocdb;DB_CLOSE_ON_EXIT=FALSE"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"
  liquibase:
    change-log: "classpath:db/master-coc.json"
    parameters:
      uuid_function:
        name: "uuid_function"
        value: "random_uuid()"
  jpa:
    show-sql: "true"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8083/realms/HBsites/protocol/openid-connect/certs"
  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "rpgtracker-coc"
    password: "rpgtracker-coc"
server:
  port: "8082"
